### ISSUE TITLE
Demo linki

### ISSUE THREAD

**Issue by mehmetakifakkus** [mustafacanp/TextGame#1]
Aslında random color projesindeki gibi bir demo linki koysanız güzel olur. Projeleriniz güzel devam edin.

**Comment by mustafacanp** [comment]
Projeyi çok detaylandığı için yarım bıraktım, o yüzden henüz demo linki koymamıştım. Değerlendirmeniz için çok teşekkürler.

**Comment by mustafacanp** [comment]
Demo linki geldi inceleyebilirsiniz, fakat proje hala yarım.
